//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class AlarmLogSet_Mapping : EntityTypeConfiguration<AlarmLogSet>
    {
        public AlarmLogSet_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("AlarmLogSet");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.AlarmLevelName).HasColumnName("AlarmLevelName").IsRequired();
              this.Property(t => t.Action).HasColumnName("Action").IsRequired();
              this.Property(t => t.TimeStamp).HasColumnName("TimeStamp");
              this.Property(t => t.AlarmConfigId).HasColumnName("AlarmConfigId");
              this.Property(t => t.CurrentValue).HasColumnName("CurrentValue").IsRequired();
              this.HasRequired(t => t.AlarmConfigSet).WithMany(t => t.AlarmLogSets).HasForeignKey(d => d.AlarmConfigId);
         }
    }
}
