//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmTerminalSet
    {
        public int Id { get; set; }
        public bool Active { get; set; }
        public bool Acknowledged { get; set; }
        public string AlarmLevelName { get; set; }
        public float MaxValue { get; set; }
        public System.DateTime SetTime { get; set; }
        public System.DateTime MaxValueTime { get; set; }
        public Nullable<System.DateTime> DeactivatedTime { get; set; }
        public double SetPoint { get; set; }
        public int Priority { get; set; }
        public int AlarmConfig_Id { get; set; }
    
        public virtual AlarmConfigSet AlarmConfigSet { get; set; }
    }
}
