//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class AlarmTerminalSet_Mapping : EntityTypeConfiguration<AlarmTerminalSet>
    {
        public AlarmTerminalSet_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("AlarmTerminalSet");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Active).HasColumnName("Active");
              this.Property(t => t.Acknowledged).HasColumnName("Acknowledged");
              this.Property(t => t.AlarmLevelName).HasColumnName("AlarmLevelName").IsRequired();
              this.Property(t => t.MaxValue).HasColumnName("MaxValue");
              this.Property(t => t.SetTime).HasColumnName("SetTime");
              this.Property(t => t.MaxValueTime).HasColumnName("MaxValueTime");
              this.Property(t => t.DeactivatedTime).HasColumnName("DeactivatedTime");
              this.Property(t => t.SetPoint).HasColumnName("SetPoint");
              this.Property(t => t.Priority).HasColumnName("Priority");
              this.Property(t => t.AlarmConfig_Id).HasColumnName("AlarmConfig_Id");
              this.HasRequired(t => t.AlarmConfigSet).WithMany(t => t.AlarmTerminalSets).HasForeignKey(d => d.AlarmConfig_Id);
         }
    }
}
