//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class AlarmConfigSet_Mapping : EntityTypeConfiguration<AlarmConfigSet>
    {
        public AlarmConfigSet_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("AlarmConfigSet");
              this.Property(t => t.Id).HasColumnName("Id").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.HIHI_Enable).HasColumnName("HIHI_Enable");
              this.Property(t => t.HIHI_Name).HasColumnName("HIHI_Name").IsRequired();
              this.Property(t => t.HIHI_LevelChange).HasColumnName("HIHI_LevelChange");
              this.Property(t => t.HIHI_Delay).HasColumnName("HIHI_Delay");
              this.Property(t => t.HI_Enable).HasColumnName("HI_Enable");
              this.Property(t => t.HI_Name).HasColumnName("HI_Name").IsRequired();
              this.Property(t => t.HI_LevelChange).HasColumnName("HI_LevelChange");
              this.Property(t => t.HI_Delay).HasColumnName("HI_Delay");
              this.Property(t => t.LO_Enable).HasColumnName("LO_Enable");
              this.Property(t => t.LO_Name).HasColumnName("LO_Name").IsRequired();
              this.Property(t => t.LO_LevelChange).HasColumnName("LO_LevelChange");
              this.Property(t => t.LO_Delay).HasColumnName("LO_Delay");
              this.Property(t => t.LOLO_Enabled).HasColumnName("LOLO_Enabled");
              this.Property(t => t.LOLO_Name).HasColumnName("LOLO_Name").IsRequired();
              this.Property(t => t.LOLO_LevelChange).HasColumnName("LOLO_LevelChange");
              this.Property(t => t.LOLO_Delay).HasColumnName("LOLO_Delay");
              this.Property(t => t.Enabled).HasColumnName("Enabled");
              this.Property(t => t.Location).HasColumnName("Location").IsRequired();
              this.HasRequired(t => t.VariableSet).WithOptional(t => t.AlarmConfigSet);
         }
    }
}
