//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace Database.Model
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PowerLogDBEntities : DbContext
    {
        static PowerLogDBEntities()
    	{ 
    		Database.SetInitializer<PowerLogDBEntities>(null);
    	}
    	
    	public PowerLogDBEntities() : base("name=PowerLogDBEntities")
        {
        }
    	
    	public PowerLogDBEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public PowerLogDBEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public PowerLogDBEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public PowerLogDBEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
    		modelBuilder.Configurations.Add(new AlarmConfigSet_Mapping());
    		modelBuilder.Configurations.Add(new AlarmLogSet_Mapping());
    		modelBuilder.Configurations.Add(new AlarmTerminalSet_Mapping());
    		modelBuilder.Configurations.Add(new DoubleLogSet_Mapping());
    		modelBuilder.Configurations.Add(new SingleHistogramSet_Mapping());
    		modelBuilder.Configurations.Add(new SingleLogSet_Mapping());
    		modelBuilder.Configurations.Add(new VariableSet_Mapping());
        }
    	
        public DbSet<AlarmConfigSet> AlarmConfigSets { get; set; }
        public DbSet<AlarmLogSet> AlarmLogSets { get; set; }
        public DbSet<AlarmTerminalSet> AlarmTerminalSets { get; set; }
        public DbSet<DoubleLogSet> DoubleLogSets { get; set; }
        public DbSet<SingleHistogramSet> SingleHistogramSets { get; set; }
        public DbSet<SingleLogSet> SingleLogSets { get; set; }
        public DbSet<VariableSet> VariableSets { get; set; }
    }
}
