//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableSet
    {
        public VariableSet()
        {
            this.DoubleLogSets = new HashSet<DoubleLogSet>();
            this.SingleHistogramSets = new HashSet<SingleHistogramSet>();
            this.SingleLogSets = new HashSet<SingleLogSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public bool DataLoggingEnabled { get; set; }
    
        public virtual AlarmConfigSet AlarmConfigSet { get; set; }
        public virtual ICollection<DoubleLogSet> DoubleLogSets { get; set; }
        public virtual ICollection<SingleHistogramSet> SingleHistogramSets { get; set; }
        public virtual ICollection<SingleLogSet> SingleLogSets { get; set; }
    }
}
