//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013.07.14 - 16:59:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using PowerMonitoring.Data.Dto;
using PowerMonitoring.Data.Poco;

namespace PowerMonitoring.Data.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="DoubleLog"/> and <see cref="DoubleLogDto"/>.
    /// </summary>
    public static partial class DoubleLogAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="DoubleLogDto"/> converted from <see cref="DoubleLog"/>.</param>
        static partial void OnDTO(this DoubleLog entity, DoubleLogDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DoubleLog"/> converted from <see cref="DoubleLogDto"/>.</param>
        static partial void OnEntity(this DoubleLogDto dto, DoubleLog entity);

        /// <summary>
        /// Converts this instance of <see cref="DoubleLogDto"/> to an instance of <see cref="DoubleLog"/>.
        /// </summary>
        /// <param name="dto"><see cref="DoubleLogDto"/> to convert.</param>
        public static DoubleLog ToEntity(this DoubleLogDto dto)
        {
            if (dto == null) return null;

            var entity = new DoubleLog();

            entity.DoubleLogId = dto.DoubleLogId;
            entity.DoubleValue = dto.DoubleValue;
            entity.TimeStamp = dto.TimeStamp;
            entity.VariableId = dto.VariableId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DoubleLog"/> to an instance of <see cref="DoubleLogDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="DoubleLog"/> to convert.</param>
        public static DoubleLogDto ToDTO(this DoubleLog entity)
        {
            if (entity == null) return null;

            var dto = new DoubleLogDto();

            dto.DoubleLogId = entity.DoubleLogId;
            dto.DoubleValue = entity.DoubleValue;
            dto.TimeStamp = entity.TimeStamp;
            dto.VariableId = entity.VariableId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="DoubleLogDto"/> to an instance of <see cref="DoubleLog"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DoubleLog> ToEntities(this IEnumerable<DoubleLogDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DoubleLog"/> to an instance of <see cref="DoubleLogDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<DoubleLogDto> ToDTOs(this IEnumerable<DoubleLog> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
