//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerMonitoring.Data.Poco
{
    #pragma warning disable 1573
    
    public partial class AlarmLog
    {
        public int AlarmLogId { get; set; }
        public string AlarmLevelName { get; set; }
        public string Action { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int VariableId { get; set; }
        public string CurrentValue { get; set; }

        public virtual AlarmConfiguration AlarmConfiguration { get; set; }
    }
}
