//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace PowerMonitoring.Data.Poco
{
    #pragma warning disable 1573
    
    public partial class Alarm
    {
        public int AlarmId { get; set; }
        public bool Active { get; set; }
        public bool Acknowledged { get; set; }
        public string AlarmLevelName { get; set; }
        public float MaxValue { get; set; }
        public System.DateTime SetTime { get; set; }
        public System.DateTime MaxValueTime { get; set; }
        public Nullable<System.DateTime> DeactivatedTime { get; set; }
        public double SetPoint { get; set; }
        public int Priority { get; set; }
        public int VariableId { get; set; }

        public virtual AlarmConfiguration AlarmConfiguration { get; set; }
    }
}
