//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013.07.14 - 16:59:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace PowerMonitoring.Data
{
    [DataContract()]
    public partial class AlarmConfigurationDto
    {
        [DataMember()]
        public Int32 VariableId { get; set; }

        [DataMember()]
        public Boolean HIHI_Enabled { get; set; }

        [DataMember()]
        public String HIHI_Name { get; set; }

        [DataMember()]
        public Double HIHI_LevelChange { get; set; }

        [DataMember()]
        public Int32 HIHI_Delay { get; set; }

        [DataMember()]
        public Boolean HI_Enabled { get; set; }

        [DataMember()]
        public String HI_Name { get; set; }

        [DataMember()]
        public Double HI_LevelChange { get; set; }

        [DataMember()]
        public Int32 HI_Delay { get; set; }

        [DataMember()]
        public Boolean LO_Enabled { get; set; }

        [DataMember()]
        public String LO_Name { get; set; }

        [DataMember()]
        public Double LO_LevelChange { get; set; }

        [DataMember()]
        public Int32 LO_Delay { get; set; }

        [DataMember()]
        public Boolean LOLO_Enabled { get; set; }

        [DataMember()]
        public String LOLO_Name { get; set; }

        [DataMember()]
        public Double LOLO_LevelChange { get; set; }

        [DataMember()]
        public Int32 LOLO_Delay { get; set; }

        [DataMember()]
        public Boolean Enabled { get; set; }

        [DataMember()]
        public String Location { get; set; }

        [DataMember()]
        public Int32 Variable_VariableId { get; set; }

        [DataMember()]
        public List<Int32> AlarmLogs_AlarmLogId { get; set; }

        [DataMember()]
        public List<Int32> Alarms_AlarmId { get; set; }

        public AlarmConfigurationDto()
        {
        }

        public AlarmConfigurationDto(Int32 variableId, Boolean hIHI_Enabled, String hIHI_Name, Double hIHI_LevelChange, Int32 hIHI_Delay, Boolean hI_Enabled, String hI_Name, Double hI_LevelChange, Int32 hI_Delay, Boolean lO_Enabled, String lO_Name, Double lO_LevelChange, Int32 lO_Delay, Boolean lOLO_Enabled, String lOLO_Name, Double lOLO_LevelChange, Int32 lOLO_Delay, Boolean enabled, String location, Int32 variable_VariableId, List<Int32> alarmLogs_AlarmLogId, List<Int32> alarms_AlarmId)
        {
			this.VariableId = variableId;
			this.HIHI_Enabled = hIHI_Enabled;
			this.HIHI_Name = hIHI_Name;
			this.HIHI_LevelChange = hIHI_LevelChange;
			this.HIHI_Delay = hIHI_Delay;
			this.HI_Enabled = hI_Enabled;
			this.HI_Name = hI_Name;
			this.HI_LevelChange = hI_LevelChange;
			this.HI_Delay = hI_Delay;
			this.LO_Enabled = lO_Enabled;
			this.LO_Name = lO_Name;
			this.LO_LevelChange = lO_LevelChange;
			this.LO_Delay = lO_Delay;
			this.LOLO_Enabled = lOLO_Enabled;
			this.LOLO_Name = lOLO_Name;
			this.LOLO_LevelChange = lOLO_LevelChange;
			this.LOLO_Delay = lOLO_Delay;
			this.Enabled = enabled;
			this.Location = location;
			this.Variable_VariableId = variable_VariableId;
			this.AlarmLogs_AlarmLogId = alarmLogs_AlarmLogId;
			this.Alarms_AlarmId = alarms_AlarmId;
        }
    }
}
