//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013.07.14 - 16:59:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace PowerMonitoring.Data.Dto
{
    [DataContract()]
    public partial class AlarmLogDto
    {
        [DataMember()]
        public Int32 AlarmLogId { get; set; }

        [DataMember()]
        public String AlarmLevelName { get; set; }

        [DataMember()]
        public String Action { get; set; }

        [DataMember()]
        public DateTime TimeStamp { get; set; }

        [DataMember()]
        public Int32 VariableId { get; set; }

        [DataMember()]
        public String CurrentValue { get; set; }

        [DataMember()]
        public Int32 AlarmConfiguration_VariableId { get; set; }

        public AlarmLogDto()
        {
        }

        public AlarmLogDto(Int32 alarmLogId, String alarmLevelName, String action, DateTime timeStamp, Int32 variableId, String currentValue, Int32 alarmConfiguration_VariableId)
        {
			this.AlarmLogId = alarmLogId;
			this.AlarmLevelName = alarmLevelName;
			this.Action = action;
			this.TimeStamp = timeStamp;
			this.VariableId = variableId;
			this.CurrentValue = currentValue;
			this.AlarmConfiguration_VariableId = alarmConfiguration_VariableId;
        }
    }
}
