//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013.07.14 - 16:59:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace PowerMonitoring.Data
{
    [DataContract()]
    public partial class AlarmDto
    {
        [DataMember()]
        public Int32 AlarmId { get; set; }

        [DataMember()]
        public Boolean Active { get; set; }

        [DataMember()]
        public Boolean Acknowledged { get; set; }

        [DataMember()]
        public String AlarmLevelName { get; set; }

        [DataMember()]
        public Single MaxValue { get; set; }

        [DataMember()]
        public DateTime SetTime { get; set; }

        [DataMember()]
        public DateTime MaxValueTime { get; set; }

        [DataMember()]
        public Nullable<DateTime> DeactivatedTime { get; set; }

        [DataMember()]
        public Double SetPoint { get; set; }

        [DataMember()]
        public Int32 Priority { get; set; }

        [DataMember()]
        public Int32 VariableId { get; set; }

        [DataMember()]
        public Int32 AlarmConfiguration_VariableId { get; set; }

        public AlarmDto()
        {
        }

        public AlarmDto(Int32 alarmId, Boolean active, Boolean acknowledged, String alarmLevelName, Single maxValue, DateTime setTime, DateTime maxValueTime, Nullable<DateTime> deactivatedTime, Double setPoint, Int32 priority, Int32 variableId, Int32 alarmConfiguration_VariableId)
        {
			this.AlarmId = alarmId;
			this.Active = active;
			this.Acknowledged = acknowledged;
			this.AlarmLevelName = alarmLevelName;
			this.MaxValue = maxValue;
			this.SetTime = setTime;
			this.MaxValueTime = maxValueTime;
			this.DeactivatedTime = deactivatedTime;
			this.SetPoint = setPoint;
			this.Priority = priority;
			this.VariableId = variableId;
			this.AlarmConfiguration_VariableId = alarmConfiguration_VariableId;
        }
    }
}
