//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013.07.14 - 16:59:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace PowerMonitoring.Data.Dto
{
    [DataContract()]
    public partial class SingleLogDto
    {
        [DataMember()]
        public Int32 SingleLogId { get; set; }

        [DataMember()]
        public Single SingleValue { get; set; }

        [DataMember()]
        public DateTime TimeStamp { get; set; }

        [DataMember()]
        public Int32 VariableId { get; set; }

        [DataMember()]
        public Int32 Variable_VariableId { get; set; }

        public SingleLogDto()
        {
        }

        public SingleLogDto(Int32 singleLogId, Single singleValue, DateTime timeStamp, Int32 variableId, Int32 variable_VariableId)
        {
			this.SingleLogId = singleLogId;
			this.SingleValue = singleValue;
			this.TimeStamp = timeStamp;
			this.VariableId = variableId;
			this.Variable_VariableId = variable_VariableId;
        }
    }
}
