//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013.07.14 - 16:59:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace PowerMonitoring.Data.Dto
{
    [DataContract()]
    public partial class VariableDto
    {
        [DataMember()]
        public Int32 VariableId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Type { get; set; }

        [DataMember()]
        public Boolean DataLoggingEnabled { get; set; }

        [DataMember()]
        public Int32 AlarmConfiguration_VariableId { get; set; }

        [DataMember()]
        public List<Int32> DoubleLogs_DoubleLogId { get; set; }

        [DataMember()]
        public List<Int32> SingleHistograms_SingleHistogramId { get; set; }

        [DataMember()]
        public List<Int32> SingleLogs_SingleLogId { get; set; }

        public VariableDto()
        {
        }

        public VariableDto(Int32 variableId, String name, String type, Boolean dataLoggingEnabled, Int32 alarmConfiguration_VariableId, List<Int32> doubleLogs_DoubleLogId, List<Int32> singleHistograms_SingleHistogramId, List<Int32> singleLogs_SingleLogId)
        {
			this.VariableId = variableId;
			this.Name = name;
			this.Type = type;
			this.DataLoggingEnabled = dataLoggingEnabled;
			this.AlarmConfiguration_VariableId = alarmConfiguration_VariableId;
			this.DoubleLogs_DoubleLogId = doubleLogs_DoubleLogId;
			this.SingleHistograms_SingleHistogramId = singleHistograms_SingleHistogramId;
			this.SingleLogs_SingleLogId = singleLogs_SingleLogId;
        }
    }
}
