//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerMonitoring.Data
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        public Variable()
        {
            this.DoubleLogs = new HashSet<DoubleLog>();
            this.SingleHistograms = new HashSet<SingleHistogram>();
            this.SingleLogs = new HashSet<SingleLog>();
        }

        public int VariableId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public bool DataLoggingEnabled { get; set; }

        public virtual AlarmConfiguration AlarmConfiguration { get; set; }
        public virtual ICollection<DoubleLog> DoubleLogs { get; set; }
        public virtual ICollection<SingleHistogram> SingleHistograms { get; set; }
        public virtual ICollection<SingleLog> SingleLogs { get; set; }
    }
}
